version: "3"

services:
  db:
    image: mysql:8.2
    restart: always
    container_name: IL_PROJECT
    environment:
      MYSQL_DATABASE: 'InfiniteLoopers'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
